name: Daily code format check
on:
  push:
    branches: [ master ]
jobs:
  dotnet-format:
    runs-on: windows-latest
    steps:
      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run dotnet format
        id: format
        uses: jfversluis/dotnet-format@v1.0.5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          action: "fix"
          workspace: "mana_lang.sln"
    
      - name: Commit files
        if: steps.format.outputs.has-changes == 'true'
        run: |
          git config --local user.name "Code Maid"
          git config --local user.email "code.maid@0xf6.moe"
          git commit -a -m 'Automated dotnet-format update'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: '[housekeeping] Automated PR to fix formatting errors'
          body: |
            Automated PR to fix formatting errors
          token: ${{ secrets.CODE_MAID_PAT }}
          committer: Code Maid <code.maid@0xf6.moe>
          author: Code Maid <code.maid@0xf6.moe>
          labels: code-quality ♻︎
          assignees: 0xF6
          reviewers: 0xF6
          branch: code-quality/codeformatting
